hofvidz/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views

from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from halls import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.home, name='home'),
    path('dashboard', views.dashboard, name='dashboard'),
    # AUTH
    path('signup', views.SignUp.as_view(), name='signup'),
    path('login', auth_views.LoginView.as_view(), name='login'),
    path('logout', auth_views.LogoutView.as_view(), name='logout'),
    # Hall
    path('halloffame/create', views.CreateHall.as_view(), name='create_hall'),
    path('halloffame/<int:pk>', views.DetailHall.as_view(), name='detail_hall'),
    path('halloffame/<int:pk>/update', views.UpdateHall.as_view(), name='update_hall'),
    path('halloffame/<int:pk>/delete', views.DeleteHall.as_view(), name='delete_hall'),
    # Video
    path('halloffame/<int:pk>/addvideo', views.add_video, name='add_video'),
    path('video/search', views.video_search, name='video_search'),
    path('video/<int:pk>/delete', views.DeleteVideo.as_view(), name='delete_video')
]

urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

halls/models.py
from django.db import models
from django.contrib.auth.models import User


class Hall(models.Model):
    title = models.CharField(max_length=255)
    user = models.ForeignKey(User, on_delete=models.CASCADE)

    def __str__(self):
        return self.title


class Video(models.Model):
    title = models.CharField(max_length=255)
    url = models.URLField()
    youtube_id = models.CharField(max_length=255)
    hall = models.ForeignKey(Hall, on_delete=models.CASCADE)

    def __str__(self):
        return self.title

halls/forms.py
from . import models
from django import forms


class VideoForm(forms.ModelForm):
    class Meta:
        model = models.Video
        fields = ['url']
        labels = {'url': 'YouTube URL'}


class SearchForm(forms.Form):
    search_term = forms.CharField(max_length=255, label='Search for Videos')

halls/views.py
from halls.forms import SearchForm
from django.shortcuts import render, redirect
from django.urls import reverse_lazy
from django.views import generic
from django.http import Http404, JsonResponse
from django.forms.utils import ErrorList

from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin

from . import models
from . import forms

import urllib
import requests

YOUTUBE_API_KEY = 'AIzaSyB97ldAKPu8tRKgQBHU-BO2MkT5-Nw3ylE'


def youtube_api_video_data_url(video_id, api_key):
    return f'https://www.googleapis.com/youtube/v3/videos?part=snippet&id={ video_id }&key={ api_key }'


def youtube_api_search_results_url(search, api_key):
    return f'https://www.googleapis.com/youtube/v3/search?part=snippet&maxResults=5&q={ search }&key={ api_key }'


def home(request):
    recent_halls = models.Hall.objects.all().order_by('-id')[:3]
    print(models.Hall.objects.all())
    if len(models.Hall.objects.all()) == 0:
        popular_halls = []
    else:
        popular_halls = [models.Hall.objects.get(pk=1), models.Hall.objects.get(pk=2), models.Hall.objects.get(pk=3)]
    return render(request, 'halls/home.html', {'recent_halls': recent_halls, 'popular_halls': popular_halls})


@login_required
def dashboard(request):
    halls = models.Hall.objects.filter(user=request.user)
    return render(request, 'halls/dashboard.html', {'halls': halls})


@login_required
def add_video(request, pk):
    form = forms.VideoForm()
    search_form = forms.SearchForm()
    hall = models.Hall.objects.get(pk=pk)

    if not hall.user == request.user:
        raise Http404

    if request.method == 'POST':
        form = forms.VideoForm(request.POST)
        if form.is_valid():
            video = models.Video()
            video.url = form.cleaned_data['url']
            video.hall = hall

            parsed_url = urllib.parse.urlparse(video.url)
            video_id = urllib.parse.parse_qs(parsed_url.query).get('v')
            if video_id:
                video.youtube_id = video_id[0]
                response = requests.get(youtube_api_video_data_url(video_id[0], YOUTUBE_API_KEY))
                try:
                    response.json()['items']
                except KeyError:
                    errors = form._errors.setdefault('url', ErrorList())
                    errors.append('Hit YouTube queries limit')
                else:
                    json = response.json()
                    title = json['items'][0]['snippet']['title']
                    video.title = title
                    video.save()
                    return redirect('detail_hall', pk)
            else:
                errors = form._errors.setdefault('url', ErrorList())
                errors.append('Needs to be a YouTube URL')

    return render(request, 'halls/add_video.html', {'form': form, 'search_form': search_form, 'hall': hall})


@login_required
def video_search(request):
    search_form = SearchForm(request.GET)
    if search_form.is_valid():
        encoded_search_term = urllib.parse.quote(search_form.cleaned_data['search_term'])
        response = requests.get(youtube_api_search_results_url(encoded_search_term, YOUTUBE_API_KEY))
        return JsonResponse(response.json())
    return JsonResponse({'error': 'Not able to validate form'})


class DeleteVideo(LoginRequiredMixin, generic.DeleteView):
    model = models.Video
    template_name = 'halls/delete_video.html'
    success_url = reverse_lazy('dashboard')

    # Make sure the loged in user owns the video
    def get_object(self):
        video = super(DeleteVideo, self).get_object()
        if not video.hall.user == self.request.user:
            raise Http404
        return video


class SignUp(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy('dashboard')
    template_name = 'registration/signup.html'

    # This method is called when valid form data has been POSTed.
    # To log a user in when the form is validated.
    def form_valid(self, form):
        view = super(SignUp, self).form_valid(form)
        username, password = form.cleaned_data.get('username'), form.cleaned_data.get('password1')
        user = authenticate(username=username, password=password)
        login(self.request, user)
        return view


class CreateHall(LoginRequiredMixin, generic.CreateView):
    model = models.Hall
    fields = ['title']
    template_name = 'halls/create_hall.html'
    success_url = reverse_lazy('dashboard')

    # This method is called when valid form data has been POSTed.
    def form_valid(self, form):
        # Adding the current user into the form
        # Required for the Hall model
        form.instance.user = self.request.user

        # Performing validation ourselves
        return super(CreateHall, self).form_valid(form)


class DetailHall(generic.DetailView):
    model = models.Hall
    template_name = 'halls/detail_hall.html'


class UpdateHall(LoginRequiredMixin, generic.UpdateView):
    model = models.Hall
    template_name = 'halls/update_hall.html'
    fields = ['title']
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(UpdateHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall


class DeleteHall(LoginRequiredMixin, generic.DeleteView):
    model = models.Hall
    template_name = 'halls/delete_hall.html'
    success_url = reverse_lazy('dashboard')

    def get_object(self):
        hall = super(DeleteHall, self).get_object()
        if not hall.user == self.request.user:
            raise Http404
        return hall

halls/templates/halls/add_video.html
{% extends 'halls/base.html' %}

{% block content %}
    <div class="container">
        <h2>Add Video to {{ hall.title }}</h2>
        <form method="POST" id="submit_video">
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for field in form %}
            <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}

            <button class="btn btn-success" type="submit">Add</button>
        </form>

        <br>

        <h2>OR</h2>
        <form>
            {% for field in search_form %}
            <div class="form-group">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}
        </form>

        <div id="search_results"></div>
        <script>
            let delayTimer;
            $('#id_search_term').keyup(function(){
                clearTimeout(delayTimer);
                $('#search_results').text('Loading...');
                delayTimer = setTimeout(function(){
                    let text = $('#id_search_term').val();
                    $.ajax({
                        url: '/video/search',
                        data: {
                            'search_term': text
                        },
                        dataType: 'json',
                        success: function(data){
                            let results = '';
                            $('#search_results').text('');

                            results += '<div class="row">';

                            if(!data['items']){
                                $('#search_results').text('Hit YouTube Queries Limit');
                            }else if(!data['items'].length){
                                $('#search_results').text('No Results');
                            }else{
                                data['items'].forEach(function(video){
                                    results += '<div class="col-md-4 mt-3"><div class="card mb-4 shadow-sm">';
                                    results += '<iframe width="100%" height="225" src="https://www.youtube.com/embed/' + video['id']['videoId'] + '" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>';
                                    results += '<div class="card-body"><p class="card-text">' + video['snippet']['title'] + '</p>';
                                    results += '<a href="#" class="btn btn-primary" onclick="addVideo(\'' + video['id']['videoId'] + '\')">Add</a></div></div></div>';
                                });
                            }

                            results += '</div>';

                            $('#search_results').append(results);
                        }
                    });
                }, 1000);
            });

            function addVideo(video_id){
                $('#id_url').val('https://www.youtube.com/watch?v=' + video_id);
                $('#submit_video').submit();
            }
        </script>
    </div>
{% endblock content %}

halls/templates/halls/base.html
<!doctype html>
<html lang="en">
{% load static %}

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <title>Hall of Fame Vidz</title>

    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">

    <link href="{% static 'custom.css' %}" rel="stylesheet">

    <link rel="shortcut icon" type="image/png" href="{% static 'favicon.png' %}" />
</head>

<body>
    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom shadow-sm">
        <h5 class="my-0 mr-md-auto font-weight-normal"><a href="{% url 'home' %}" class="text-dark">Hall of Fame Vidz</a></h5>
        <nav class="my-2 my-md-0 mr-md-3">
            {% if user.is_authenticated %}
            <a class="p-2 text-dark" href="{% url 'dashboard' %}">Dashboard</a>
            <a class="p-2 text-dark" href="{% url 'logout' %}">Log Out</a>
            {% else %}
            <a class="p-2 text-dark" href="{% url 'login' %}">Log In</a>
            {% endif %}
        </nav>
        {% if user.is_authenticated == False %}
        <a class="btn btn-outline-primary" href="{% url 'signup' %}">Sign up</a>
        {% endif %}
    </div>

    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>

    {% block content %}
    {% endblock %}

</body>

</html>

halls/templates/halls/create_hall.html
{% extends 'halls/base.html' %}

{% block content %}
    <div class="container">
        <h2>Create Hall of Fame</h2>
        <form method="POST">
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for field in form %}
            <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}
            <button class="btn btn-success" type="submit">Create</button>
        </form>
    </div>
{% endblock content %}

halls/templates/halls/dashboard.html
{% extends 'halls/base.html' %}

{% block content %}
<div class="container">
    <div class="text-center">
        <h1>{{ user.username }}'s Hall of Fames</h1>
        <a href="{% url 'create_hall' %}" class="btn btn-primary">Create New Hall of Fame</a>
    </div>

    {% for hall in halls %}
    <h2><a href="{% url 'detail_hall' hall.pk %}">{{ hall.title }}</a></h2>
    <a href="{% url 'update_hall' hall.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'add_video' hall.pk %}" class="btn btn-primary">Add Video</a>
    <a href="{% url 'delete_hall' hall.pk %}" class="btn btn-danger">Delete</a>

    <div class="row">
        {% for video in hall.video_set.all %}
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                <div class="card-body"><p class="card-text">{{ video.title }}</p></div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

</div>
{% endblock content %}

halls/templates/halls/delete_hall.html
{% extends 'halls/base.html' %}

{% block content %}
    <div class="container">
        <h2>Are you sure you want to delete this Hall of Fame?</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Delete</button>
        </form>

        <br>

        <h2><a href="{% url 'detail_hall' hall.id %}">{{ hall.title }}</a></h2>
    </div>
{% endblock content %}

halls/templates/halls/delete_video.html
{% extends 'halls/base.html' %}

{% block content %}
    <div class="container">
        <h2>Are you sure you want to delete this video from your {{ video.hall.title }} Hall of Fame?</h2>
        <form method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <button class="btn btn-danger" type="submit">Delete</button>
        </form>


        <div class="row">
            <div class="col-md-4 mt-3">
                <div class="card mb-4 shadow-sm">
                    <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                    <div class="card-body"><p class="card-text">{{ video.title }}</p></div>
                </div>
            </div>
        </div>
    </div>
{% endblock content %}

halls/templates/halls/detail_hall.html
{% extends 'halls/base.html' %}

{% block content %}
<div class="container">
    <h1>{{ hall.title }}</h1>
    <h4 class="text-muted">{{ hall.user.username }}</h4>

    {% if user.id == hall.user.id %}
    <a href="{% url 'update_hall' hall.pk %}" class="btn btn-primary">Edit</a>
    <a href="{% url 'add_video' hall.pk %}" class="btn btn-primary">Add Video</a>
    <a href="{% url 'delete_hall' hall.pk %}" class="btn btn-danger">Delete</a>
    {% endif %}

    <div class="row">
        {% for video in hall.video_set.all %}
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                <div class="card-body">
                    <p class="card-text">{{ video.title }}</p>

                    {% if user.id == hall.user.id %}
                    <a href="{% url 'delete_video' video.pk %}" class="btn btn-danger btn-sm">Delete</a>
                    {% endif %}

                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% endblock content %}

halls/templates/halls/home.html
{% extends 'halls/base.html' %}

{% block content %}
<section class="jumbotron text-center mt-n3">
    <div class="container">
        <h1 class="jumbotron-heading">What's your personal Hall of Fame?</h1>
        <p class="lead text-muted">You what they are. They're your go to videos. You have a top 10 list and it's time to share them with the world. Click the button below to get started.</p>
        <p>
            <a href="{% url 'create_hall' %}" class="btn btn-primary">Create Your Hall of Fame</a>
        </p>
    </div>
</section>
<div class="container">
    <h1 class="text-center">Popular Hall of Fames</h1>

    {% for hall in popular_halls %}
    <h2><a href="{% url 'detail_hall' hall.pk %}">{{ hall.title }}</a></h2>

    <div class="row">
        {% for video in hall.video_set.all %}
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                <div class="card-body"><p class="card-text">{{ video.title }}</p></div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}


    <h1 class="text-center">Recent Hall of Fames</h1>

    {% for hall in recent_halls %}
    <h2><a href="{% url 'detail_hall' hall.pk %}">{{ hall.title }}</a></h2>

    <div class="row">
        {% for video in hall.video_set.all %}
        <div class="col-md-4 mt-3">
            <div class="card mb-4 shadow-sm">
                <iframe width="100%" height="225" src="https://www.youtube.com/embed/{{ video.youtube_id }}" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>

                <div class="card-body"><p class="card-text">{{ video.title }}</p></div>
            </div>
        </div>
        {% endfor %}
    </div>
    {% endfor %}

</div>
{% endblock content %}

halls/templates/halls/update_hall.html
{% extends 'halls/base.html' %}

{% block content %}
    <div class="container">
        <h2>Edit Hall of Fame</h2>
        <form method="POST">
            {% csrf_token %}
            {% load widget_tweaks %}

            {% for field in form %}
            <div class="form-group {% if field.errors %}alert alert-danger{% endif %}">
                {{ field.errors }}
                {{ field.label_tag }}
                {% render_field field class="form-control" %}
            </div>
            {% endfor %}

            <button class="btn btn-success" type="submit">Save</button>
        </form>
        <br>
        <a class="btn btn-danger" href="{% url 'delete_hall' hall.id %}">Delete this Hall of Fame</a>
    </div>
{% endblock content %}